;(function($){var boxs,ul,li,len,index,speed,start,isScrolling,deltaX,interval,pw=320,isauto,btn,ibi,srcs,hhw,las=true,dely;var methods={resets:function(_options){if(index==1){return;}
index=1;methods.slide(1,300);return false;},setup:function(_options){var q=$.extend({},$.fn.vganswiper.defaults,_options);boxs=this[0];ul=boxs.children[0];li=$(ul).children();len=li.length;index=1;speed=300;ibi=q.bi;srcs=q.srcs;isauto=q.auto;dely=q.delay;pw=Math.ceil("getBoundingClientRect"in boxs?boxs.getBoundingClientRect().width:boxs.offsetWidth);hhw=pw>640?640:pw*ibi;if(len<2){return;}
var alen=len;var fmove=-pw;while(alen--){li.eq(alen).css("width",pw+"px");}
ul.style.width=pw*(len+2)+"px";if(ibi!=0){ul.style.height=hhw+"px";}
var cd1=li.eq(0).clone();var cd2=li.eq(len-1).clone();$(ul).append(cd1);$(ul).prepend(cd2);li=$(ul).children();if(q.showbtn){var btns="";for(var i=0;i<len;i++){if(i==0){btns+='<i class="on"></i>';}else{btns+="<i></i>";}}
$("#"+q.btn).html(btns);}
btn=$("#"+q.btn).children();ul.style.MozTransform=ul.style.webkitTransform=ul.style.transform="translate3d("+fmove+"px,0,0)";ul.style.msTransform=ul.style.OTransform="translateX("+fmove+"px)";methods.addlisten();if(isauto){methods.sbegins();}},addlisten:function(){ul.addEventListener("touchstart",methods.t_start,false);ul.addEventListener("touchmove",methods.t_move,false);ul.addEventListener("touchend",methods.t_end,false);ul.addEventListener("webkitTransitionEnd",methods.transitionEnd,false);ul.addEventListener("msTransitionEnd",methods.transitionEnd,false);ul.addEventListener("oTransitionEnd",methods.transitionEnd,false);ul.addEventListener("transitionend",methods.transitionEnd,false);window.addEventListener("resize",methods.wres,false);},t_start:function(e){start={pageX:e.touches[0].pageX,pageY:e.touches[0].pageY,time:Number(new Date())};isScrolling=undefined;deltaX=0;var b=ul.style;b.webkitTransitionDuration=b.MozTransitionDuration=b.msTransitionDuration=b.OTransitionDuration=b.transitionDuration="0ms";if(index>=len+1){b.MozTransform=b.webkitTransform=b.transform="translate3d("+ -pw+"px,0,0)";b.msTransform=b.OTransform="translateX("+ -pw+"px)";index=1;}
if(index==0){b.MozTransform=b.webkitTransform=b.transform="translate3d("+ -pw*len+"px,0,0)";b.msTransform=b.OTransform="translateX("+ -pw*len+"px)";index=len;}
e.stopPropagation();},t_move:function(e){if(e.touches.length>1||e.scale&&e.scale!==1){return;}
deltaX=e.touches[0].pageX-start.pageX;if(typeof isScrolling=="undefined"){isScrolling=!!(isScrolling||Math.abs(deltaX)<Math.abs(e.touches[0].pageY-start.pageY));}
if(!isScrolling){if(isauto){clearTimeout(interval);}
ul.style.MozTransform=ul.style.webkitTransform=ul.style.transform="translate3d("+(deltaX-index*pw)+"px,0,0)";ul.style.msTransform=ul.style.OTransform="translateX("+(deltaX-index*pw)+"px)";e.preventDefault();e.stopPropagation();}},t_end:function(e){var b=Number(new Date())-start.time<250&&Math.abs(deltaX)>20||Math.abs(deltaX)>80;if(!isScrolling){methods.slide(index+(b?deltaX<0?1:-1:0),speed);}
e.stopPropagation();},wres:function(){var xpw=Math.ceil("getBoundingClientRect"in boxs?boxs.getBoundingClientRect().width:boxs.offsetWidth);if(xpw<1){return false;}else{pw=xpw;}
hhw=pw>640?640:pw*ibi;var klen=len+2;while(klen--){li.eq(klen).css("width",pw+"px");}
ul.style.width=pw*(len+2)+"px";if(ibi!=0){ul.style.height=hhw+"px";}
var b=ul.style;b.webkitTransitionDuration=b.MozTransitionDuration=b.msTransitionDuration=b.OTransitionDuration=b.transitionDuration="0ms";b.MozTransform=b.webkitTransform=b.transform="translate3d("+ -index*pw+"px,0,0)";b.msTransform=b.OTransform="translateX("+ -index*pw+"px)";},transitionEnd:function(a){if(isauto){methods.sbegins();}},slide:function(a,c){if(a>len+1){a=len;}
var b=ul.style;b.webkitTransitionDuration=b.MozTransitionDuration=b.msTransitionDuration=b.OTransitionDuration=b.transitionDuration=c+"ms";b.MozTransform=b.webkitTransform=b.transform="translate3d("+ -(a*pw)+"px,0,0)";b.msTransform=b.OTransform="translateX("+ -(a*pw)+"px)";index=a;var ix;if(index==1||index>=len+1){ix=0;}else{if(index==0){ix=len-1;if(las){console.log(2);var lvma=li.eq(len).find("img");var lva=lvma.attr(srcs);if(lva){lvma.attr("src",lva).removeAttr(srcs);}
las=false;}}else{ix=index-1;}}
btn.eq(ix).addClass("on").siblings().removeClass("on");var lvm=li.eq(index).find("img");var lv=lvm.attr(srcs);if(lv){lvm.attr("src",lv).removeAttr(srcs);}},snext:function(){clearTimeout(interval);var cur=index+1;if(cur==len+1){cur=1;}
methods.slide(cur,speed);},sbegins:function(){interval=isauto?setTimeout(function(){methods.snext();},dely):0;}};$.fn.vganswiper=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.setup.apply(this,arguments);}else{alert('Method'+method+'does not exist');}};$.fn.vganswiper.defaults={srcs:"lazy",auto:true,btn:"btn",bi:0,showbtn:true,author:"vganchou",delay:4e3};})(af);